### ISSUE TITLE
Can't install on Windows store version of Paint.NET

### ISSUE THREAD

**Issue by iOrange** [BoltBait/CodeLab#15]
The installer can't find Paint.NET. I'm using Windows Store version of Paint.NET.
I'll try building the plugin from sources, but would be nice to be able to install the release for those users who can't build for themselves.

**Comment by toehead2001** [comment]
The "Generate VS Solution" needs to modified slightly to work with the AppX version.

It generates currently generates stuff like this:
```
<Reference Include="PaintDotNet.Core">
  <HintPath>C:\Program Files\WindowsApps\dotPDNLLC.paint.net_4.105.6913.0_x64__snvyr12g2rhj0\PaintDotNet.Core.dll</HintPath>
</Reference>
```

Those file paths are restricted by Windows, and so Visual Studio won't be able to use them.

The required assemblies are only available to reference, if the classic paint.net is installed. So should we just disable the "Generate VS Solution" button when CodeLab is run in the AppX version?

**Comment by BoltBait** [comment]
Maybe if the user presses the button we give a message that this function is only available with the classic version.

**Comment by iOrange** [comment]
Excuse me guys, but my issue is that I can't install CodeLab at all if I have Windows Store version of Paint.NET
The installer simply don't see it.

**Comment by toehead2001** [comment]
Yes, don't worry, we know.
But we need to fix other issues first. Allowing people to install CodeLab when it's in a semi-broken state is not a good idea.

By the way, if you're unaware, AppX means Windows Store version.

**Comment by BoltBait** [comment]
Now that @toehead2001 has fixed CodeLab itself, I'll fix the installer.

You'll be able to install the next version of CodeLab for the store version of Paint.NET.

You'll even be able to build DLL files.  You just won't be able to create a Visual Studio project from your CodeLab script.

**Comment by BoltBait** [comment]
I updated the Installer.

@iOrange you'll be able to install CodeLab to the Store Version of Paint.NET in the next release of CodeLab.

I will be publishing the next update to CodeLab when Rick publishes the next release of Paint.NET.  (I don't know when that will be, but my feeling is that it will be fairly soon now.)

**Comment by iOrange** [comment]
Thanks guys!
