### ISSUE TITLE
Template dialog is getting cramped

### ISSUE THREAD

**Issue by toehead2001** [BoltBait/CodeLab#22]
I think the dialog would be easier to understand and more visually appealing if it the layout was something like this:

![TemplateForm](https://user-images.githubusercontent.com/11582193/54650104-c3b4aa80-4aa4-11e9-9d0f-bb9c3653d028.png)
(mockup made in paint.net)

**Comment by BoltBait** [comment]
That looks good.  I'll revise for the next release.

**Comment by BoltBait** [comment]
![NewSourceUI](https://user-images.githubusercontent.com/14893317/54734250-83fcca00-4b5b-11e9-9927-2f09c7ef442c.png)
