### ISSUE TITLE
Upgrade to Visual Studio 2019

### ISSUE THREAD

**Issue by BoltBait** [BoltBait/CodeLab#24]

**Comment by toehead2001** [comment]
Right now, the solution will work with both VS2017 and VS2019.

VS2019 would only be required if we started using C# 8.0 features. Or when we switch to .NET Core... when Paint.NET itself does.

**Comment by BoltBait** [comment]
This was just a reminder for me to upgrade my VS at home.

**Comment by BoltBait** [comment]
And... I'm upgraded.
