### ISSUE TITLE
Waiting for the code to start compiling is extremely frustrating

### ISSUE THREAD

**Issue by JimmyCushnie** [BoltBait/CodeLab#37]
When you make a change to the code, compiling doesn't start until after a 3 second countdown. This is aggravating when I'm trying to quickly iterate, making small changes and seeing how they effect the image. I am forced to wait those 3 seconds doing nothing, as there's no way to manually trigger a recompile.

I propose the following changes to improve the experience of working in codelab:

1. As soon as the user saves their code, a recompile is triggered immediately
1. Add a GUI indicator while code is compiling

**Comment by toehead2001** [comment]
> as there's no way to manually trigger a recompile.

Doesn't the `Build` button at the bottom of the window trigger a recompile for you?


> Add a GUI indicator while code is compiling

The compile should be very quick (a fraction of a second). What kind of times are you experiencing?

**Comment by JimmyCushnie** [comment]
...oh damn, I totally missed the build button. Thank you, that's what I need.

Is there a hotkey? I'd rather not switch between keyboard/mouse while coding.

**Comment by toehead2001** [comment]
There's currently no hotkey.
`Ctrl`+`R` isn't being used for anything, so that would be a suitable candidate.
