### ISSUE TITLE
Add a hotkey to build and run the code

### ISSUE THREAD

**Issue by JimmyCushnie** [BoltBait/CodeLab#38]
Currently, to build and run the code, you must press a GUI button with the mouse. I would like to be able to do this from the keyboard, so that I don't have to move my hands while quickly iterating on some code.

@toehead2001 suggested Ctrl+R [here](https://github.com/BoltBait/CodeLab/issues/37#issuecomment-640423697). I think Ctrl+S would also work well: compile the code whenever the code is saved.

**Comment by JimmyCushnie** [comment]
Bless!

**Comment by BoltBait** [comment]
This will be in the next build.  The key to build will be F6 (same as in Visual Studio).
