### ISSUE TITLE
Use AssemblyLoadContext to load the generated Assembly

### ISSUE THREAD

**Issue by rickbrew** [BoltBait/CodeLab#40]
In PDN 4.3, effect plugins are now loaded into separate `AssemblyLoadContext`s which has a few benefits.

First, it means dependencies can be "plugin local" -- two plugins can have a dependency with the same file name but different versions (or they could just be entirely different and accidentally have the same name), and as long as the plugins are in separate directories it will work out because they only load and use types from their own local dependency.

Second, `AssemblyLoadContext`s are _collectible_. This means they can be unloaded and garbage collected! In PDN, I use this to unload an ALC if the DLL I loaded into it winds up having zero plugins in it -- this happens when trying to gather effects from a shared library, for instance, which obviously won't have effects in it. Also happens if none of the plugins _could_ be loaded, like if they were blocked or threw exceptions in their constructors.

Since CodeLab is constantly loading newly compiled generated assemblies, this could be a very good thing.

You don't need to use the `ALC.Unload()` method, as they'll be GC'd automatically as long as you're no longer holding onto the ALC. Basically you just hold onto a tuple of `(AssemblyLoadContext, Assembly)` instead of just `Assembly` and it'll happen automatically (non-deterministically, of course). In fact, I don't recommend calling `Unload()` as it can then get out-of-order with finalizing instances of types that were in the assembly (not a good thing).

You do need to implement a derived class from `ALC`, but thankfully it's simple. In the PDN source, it's `./PaintDotNet/AppModel/PluginAssemblyLoadContext.cs`. And then instead of `Assembly.Load*()` you use `AssemblyLoadContext.Load*()`. You then use the `Assembly` as you normally would.

If you use `Assembly.Load()` then it will load into the default load context, which you don't want for something like CodeLab.

I'm happy to help out with this, and it should be a simple change from what I saw in `ScriptBuilder.cs`

**Comment by toehead2001** [comment]
> I'm happy to help out with this, and it should be a simple change from what I saw in ScriptBuilder.cs

I've just merged the dotnet5 changes, so feel free to make your suggested changes.

**Comment by rickbrew** [comment]
I'm trying to build CodeLab locally, but it doesn't seem to be copying over the DLLs for the nuget packages. Have you seen this? The build is fine, but the DLLs just aren't there 🤔 This means the post-build event which copies everything fails, and the plugin doesn't work in Paint.NET either. (yup, i'm running VS as admin so it can copy over to Program Files)

![image](https://user-images.githubusercontent.com/10873410/130646797-1c143223-d317-4498-a8d7-e953d62563f7.png)

**Comment by toehead2001** [comment]
I just pushed a change to the .csproj that should copy the Nuget assemblies to the Bin directories.

**Comment by toehead2001** [comment]
cce80a1c71e0cc59be07fde699e44d476e985b8c

**Comment by rickbrew** [comment]
Okay it works now, thanks!
