### ISSUE TITLE
Render loop reports invalid x / y and width / height values??

### ISSUE THREAD

**Issue by MisterSirCode** [BoltBait/CodeLab#49]
Ive been trying to get the valid x positions for hours.
Every time I grab the X or Y positions and convert them to a byte, they cycle through loops of 128...
If I grab the width / right or height / bottom values, it also says 128

I need the X values of the entire image or selection.. not little 128 sections... Why is this behaving like this... its extremely irritating..

Here I selected just a bunch of random squares... as you can see... its just 128x128 blocks extending from 0, 0

![image](https://user-images.githubusercontent.com/44554976/149252754-523e01e8-a7dd-4988-8bb7-b3682e77c466.png)

I get that this is used for parallel work.. but this is absolutely useless when trying to use this for a mathematical purpose that scales along the entire image width... not little tiny 128x128 blocks...

![image](https://user-images.githubusercontent.com/44554976/149253128-78072154-a5ee-40ee-a21b-8df0b832da6a.png)

This is not ideal..

**Comment by BoltBait** [comment]
This is not a bug.  CodeLab is working as designed.

Closed.

Now, within the inner loops of the default CodeLab script, the X and Y variables describe the location of the working pixel within the current ROI (that is, X and Y are offsets into the current Rectangle).  So, if you want to know the ACTUAL pixel location in regards to the entire canvas, you need to add X to the rectangle's left location and add Y to the rectangle's top location, like this:

    int ActualX = rect.Left + x;
    int ActualY = rect.Top + y;

Finally, you can't store a X or Y into a byte variable because they're too big to fit.

byte holds -128 to 127

Now, if you're looking for 0 to 255 range, you need to use an "unsigned byte" type.

But, in reality, those addresses can be much bigger than can fit into even an unsigned byte. You should be storing those as an int.

**Comment by MisterSirCode** [comment]
@BoltBait Ive tried using the rect bounds, they report 0

Basically all I want is to use an entire range of values for the entire image. I can easily map that to 255 to make a gradient based on the position... but I cant even get the actual positon.

**Comment by rickbrew** [comment]
Casting to `byte` is just lopping off the lower 8-bits of the integer. You need to clamp.

This isn't a CodeLab issue, it's a basic C# programming language question.

**Comment by rickbrew** [comment]
(btw, `byte` is `[0, 255]`, whereas `sbyte` is `[-128, +127]`)

**Comment by MisterSirCode** [comment]
> This is not a bug. CodeLab is working as designed.
> 
> Closed.
> 
> Now, within the inner loops of the default CodeLab script, the X and Y variables describe the location of the working pixel within the current ROI (that is, X and Y are offsets into the current Rectangle). So, if you want to know the ACTUAL pixel location in regards to the entire canvas, you need to add X to the rectangle's left location and add Y to the rectangle's top location, like this:
> 
> ```
> int ActualX = rect.Left + x;
> int ActualY = rect.Top + y;
> ```
> 
> Finally, you can't store a X or Y into a byte variable because they're too big to fit.
> 
> byte holds -128 to 127
> 
> Now, if you're looking for 0 to 255 range, you need to use an "unsigned byte" type.
> 
> But, in reality, those addresses can be much bigger than can fit into even an unsigned byte. You should be storing those as an int.

Sorry for the super late reply / necro, but you should atleast know this for the future.
Your suggestion didnt work for me.. at all.

Instead, I used the source bounds and had to scale it based off of the surface width... This is an absolute pain in the ass to work with for some reason.. The drawing logic makes zero sense. When I print those lines there for y for example, I get a mix of hundreds of zeroes and a few random ints. It breaks all basic drawing logic I can understand.. like, it just doesnt make sense some of the stuff that it outputs.

Like basic scaling math applied to the selection boxes does all sorts of wierd shit.. It doesnt make any sense when comparing it to... well.. any other drawing utility out there

This is the only way I could find to draw actual working UVs..

```cs
    Rectangle selection = src.Bounds;
    int width = selection.Width;
    int height = selection.Height;
    double ws = (Double)width / 255;
    double hs = (Double)height / 255;
```
(For Bound Logic)

and for actual positions + UVs:
```cs
    ColorBgra currentPixel;
    for (int y = rect.Top; y < height; y++)
    {
        if (IsCancelRequested) return;
        for (int x = rect.Left; x < width; x++)
        {
            if (IsCancelRequested) return;
            currentPixel = src[x,y];
            currentPixel.R = (byte)Math.Clamp(x / ws, 0, 255);
            currentPixel.G = (byte)Math.Clamp(y / hs, 0, 255);
            currentPixel.B = 0;
            currentPixel.A = 255;
            dst[x,y] = currentPixel;
        }
    }
```
![image](https://user-images.githubusercontent.com/44554976/196056322-bfa808e5-ae88-48e9-8eef-677c3d1f4bb5.png)
