### ISSUE TITLE
Switch to CARETLINEFRAME

### ISSUE THREAD

**Issue by toehead2001** [BoltBait/CodeLab#5]
The `CARETLINEFRAME` option was added a while ago in Scintilla v3.7.5, but ScintillaNET has yet to update its bundled binary.

Waiting on upstream.  I may need to create a Pull Request on that project.

![caretlineframe](https://user-images.githubusercontent.com/11582193/44501025-eef42a00-a67a-11e8-9563-4224c22a3fd6.png)

**Comment by BoltBait** [comment]
If you change this, make it optional.

I'm not a fan.
