### ISSUE TITLE
Line Number Rendering Issue

### ISSUE THREAD

**Issue by Andronomos** [BoltBait/CodeLab#57]
Line numbers do not render correctly, then are cut off by the window.

CodeLab v6.8
Paint.Net v5.0.9

![2023-09-11_050954](https://github.com/BoltBait/CodeLab/assets/29628786/7dcf3b14-96d5-4bd9-8f1e-dca7edf5ea84)

My settings:
![2023-09-11_051310](https://github.com/BoltBait/CodeLab/assets/29628786/5c62580f-ad7e-44dd-8f1f-296acc634b20)

**Comment by rickbrew** [comment]
Same for me
<img width="444" alt="image" src="https://github.com/BoltBait/CodeLab/assets/10873410/4ae94f6e-a3f1-41a9-b717-a614fef76fe9">

**Comment by rickbrew** [comment]
Is it perhaps a high-DPI issue? I'm at 1.5x / 144 DPI

**Comment by rickbrew** [comment]
Hmm, now it's working correctly

Maybe it doesn't do the layout correctly until you close and restart CodeLab?

![image](https://github.com/BoltBait/CodeLab/assets/10873410/3520b516-590a-47d6-b183-488c7780c6ce)

**Comment by rickbrew** [comment]
Yeah that seems to cause it.

1. Open up CodeLab _without_ line numbers enabled
2. Enable line numbers, notice how it renders wrong
3. Close CodeLab
4. Open CodeLab again. Notice how it renders correctly

**Comment by Andronomos** [comment]
Yep, you can easily replicate this by disabling line numbers, closing CodeLab, re opening it and re enabling line numbers.

**Comment by Andronomos** [comment]
I've always wanted to contribute back to Paint.Net, this may have been a minor bug fix but I'm glad I reported it.
