### ISSUE TITLE
Icon PNG should not be limited to 16x16

### ISSUE THREAD

**Issue by rickbrew** [BoltBait/CodeLab#63]
Paint.NET is fine with any image size, it will just fit it into a 16[dip](https://en.wikipedia.org/wiki/Device-independent_pixel) x 16dip area. For high-DPI systems, supplying a 32x32px image or even a 64x64px image can help the effect's icon to look better. Sharper, less blurry.

![image](https://github.com/BoltBait/CodeLab/assets/10873410/3af07212-5e0f-45a1-b4c1-5a5d6ca869a8)

**Comment by BoltBait** [comment]
CodeLab does silently allow a 32x32 image as well.

**Comment by toehead2001** [comment]
The size check should do this:
```
// ensure the icon is square, and is at least 16 x 16
if (size.Width != size.Height || size.Width < 16)
{
	// error here
}
```
